import { PosterType } from './types';
export const imgSize = {
  og: {
    width: 540,
    height: 380,
    ratio: 2,
  },
  download: {
    width: 345,
    height: 553,
    ratio: 2,
  },
  poster: {
    width: 1000,
    height: 500,
    ratio: 1.5,
  },
  discord: {
    width: 1250,
    height: 500,
    ratio: 1.28,
  },
  badge: {
    width: 400,
    height: 400,
    ratio: 2,
  },
  thumbnail: {
    width: 1000,
    height: 500,
    ratio: 1,
  },
};

export const BG_TYPES = [
  [
    { bg: 'bg0-0.jpeg', textColor: 'white' },
    { bg: 'bg0-1.jpeg', textColor: 'white' },
    { bg: 'bg0-2.jpeg', textColor: 'white' },
    { bg: 'bg0-3.jpeg', textColor: 'white' },
  ],
  [
    { bg: 'bg1-0.jpeg', textColor: 'black' },
    { bg: 'bg1-1.jpeg', textColor: 'black' },
    { bg: 'bg1-2.jpeg', textColor: 'black' },
    { bg: 'bg1-3.jpeg', textColor: 'black' },
    { bg: 'bg1-4.jpeg', textColor: 'black' },
  ],
  [
    { bg: 'bg2-0.jpeg', textColor: 'white' },
    { bg: 'bg2-1.jpeg', textColor: 'white' },
    { bg: 'bg2-2.jpeg', textColor: 'white' },
    { bg: 'bg2-3.jpeg', textColor: 'white' },
  ],
  [
    { bg: 'bg3-0.jpeg', textColor: 'black' },
    { bg: 'bg3-1.jpeg', textColor: 'black' },
    { bg: 'bg3-2.jpeg', textColor: 'black' },
    { bg: 'bg3-3.jpeg', textColor: 'black' },
  ],
  [
    { bg: 'bg4-0.jpeg', textColor: 'black' },
    { bg: 'bg4-1.jpeg', textColor: 'black' },
    { bg: 'bg4-2.jpeg', textColor: 'black' },
    { bg: 'bg4-3.jpeg', textColor: 'black' },
    { bg: 'bg4-4.jpeg', textColor: 'black' },
  ],
  [
    { bg: 'bg5-0.jpeg', textColor: 'black' },
    { bg: 'bg5-1.jpeg', textColor: 'black' },
    { bg: 'bg5-2.jpeg', textColor: 'black' },
    { bg: 'bg5-3.jpeg', textColor: 'black' },
    { bg: 'bg5-4.jpeg', textColor: 'black' },
    { bg: 'bg5-5.jpeg', textColor: 'black' },
  ],
  [
    { bg: 'bg6-0.jpeg', textColor: 'white' },
    { bg: 'bg6-1.jpeg', textColor: 'white' },
    { bg: 'bg6-2.jpeg', textColor: 'white' },
    { bg: 'bg6-3.jpeg', textColor: 'white' },
    { bg: 'bg6-4.jpeg', textColor: 'white' },
  ],
  [
    { bg: 'bg7-0.jpeg', textColor: 'white' },
    { bg: 'bg7-1.jpeg', textColor: 'white' },
    { bg: 'bg7-2.jpeg', textColor: 'white' },
    { bg: 'bg7-3.jpeg', textColor: 'white' },
    { bg: 'bg7-4.jpeg', textColor: 'white' },
  ],
  [
    { bg: 'bg8-0.jpeg', textColor: 'white' },
    { bg: 'bg8-1.jpeg', textColor: 'white' },
    { bg: 'bg8-2.jpeg', textColor: 'white' },
    { bg: 'bg8-3.jpeg', textColor: 'white' },
  ],
  [
    { bg: 'bg9-0.jpeg', textColor: 'white' },
    { bg: 'bg9-1.jpeg', textColor: 'white' },
    { bg: 'bg9-2.jpeg', textColor: 'white' },
    { bg: 'bg9-3.jpeg', textColor: 'white' },
    { bg: 'bg9-4.jpeg', textColor: 'white' },
  ],
  [
    { bg: 'bg10-0.jpeg', textColor: 'black' },
    { bg: 'bg10-1.jpeg', textColor: 'black' },
    { bg: 'bg10-2.jpeg', textColor: 'black' },
    { bg: 'bg10-3.jpeg', textColor: 'black' },
    { bg: 'bg10-4.jpeg', textColor: 'black' },
  ],
  [
    { bg: 'bg11-0.jpeg', textColor: 'white' },
    { bg: 'bg11-1.jpeg', textColor: 'white' },
    { bg: 'bg11-2.jpeg', textColor: 'white' },
    { bg: 'bg11-3.jpeg', textColor: 'white' },
    { bg: 'bg11-4.jpeg', textColor: 'white' },
    { bg: 'bg11-5.jpeg', textColor: 'white' },
    { bg: 'bg11-6.jpeg', textColor: 'white' },
    { bg: 'bg11-7.jpeg', textColor: 'white' },
    { bg: 'bg11-8.jpeg', textColor: 'white' },
    { bg: 'bg11-9.jpeg', textColor: 'white' },
  ],
  [
    { bg: 'bg12-0.jpeg', textColor: 'white' },
    { bg: 'bg12-1.jpeg', textColor: 'white' },
    { bg: 'bg12-2.jpeg', textColor: 'white' },
    { bg: 'bg12-3.jpeg', textColor: 'white' },
    { bg: 'bg12-4.jpeg', textColor: 'white' },
  ],
  [
    { bg: 'bg13-0.jpeg', textColor: 'black' },
    { bg: 'bg13-1.jpeg', textColor: 'black' },
    { bg: 'bg13-2.jpeg', textColor: 'black' },
    { bg: 'bg13-3.jpeg', textColor: 'black' },
    { bg: 'bg13-4.jpeg', textColor: 'black' },
  ],
  [
    { bg: 'bg14-0.jpeg', textColor: 'black' },
    { bg: 'bg14-1.jpeg', textColor: 'black' },
    { bg: 'bg14-2.jpeg', textColor: 'black' },
    { bg: 'bg14-3.jpeg', textColor: 'black' },
    { bg: 'bg14-4.jpeg', textColor: 'black' },
  ],
  [
    { bg: 'bg15-0.jpg', textColor: 'white' },
    { bg: 'bg15-1.jpg', textColor: 'white' },
    { bg: 'bg15-2.jpg', textColor: 'white' },
    { bg: 'bg15-3.jpg', textColor: 'white' },
    { bg: 'bg15-4.jpg', textColor: 'white' },
  ],
];
